config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root 'welcome#index'

  
    resources :cats
	post 'listenerstats' => 'listenerstats#index', :as => :listenerstats
	get 'listenerstats' => 'listenerstats#index', :as => :listenerstats_get
  
  
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :name, presence: true,
                    length: { minimum: 3 }
  validates :color, presence: true,
                    length: { minimum: 3 }
  validates :race, presence: true,
                    length: { minimum: 3 }					
  validates :gender, presence: true,
                    length: { minimum: 1 }
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
	def index
	@cats = Cat.all
	end
	def show
		@cat = Cat.find(params[:id])
	end
	def new
		@cat = Cat.new
	end
	def edit
	  @cat = Cat.find(params[:id])
	end	
	def create
		@cat = Cat.new(cat_params)
		
		if @cat.save
			redirect_to @cat
		else
			render 'new'
		end
	end
	def update
	  @cat = Cat.find(params[:id])
	 
	  if @cat.update(cat_params)
		redirect_to @cat
	  else
		render 'edit'
	  end
	end
	def destroy
	  @cat = Cat.find(params[:id])
	  @cat.destroy
	 
	  redirect_to cats_path
	end	
	private
		def cat_params
		params.require(:cat).permit(:name, :color, :race, :gender)
		end	
end

app/controllers/listenerstats_controller.rb
class ListenerstatsController < ApplicationController
  def index
	@name=params[:listenerName] 
	@startDate=params[:from]
	@endDate=params[:to]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/cats/_form.html.erb
<%= form_for @cat do |f| %>
 
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cat.errors.count, "error") %> prohibited
        this cat from being saved:
      </h2>
      <ul>
        <% @cat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>
  
  <p>
    <%= f.label :breed %><br>
    <%= f.text_field :race %>
  </p>  
  <p>
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </p>  
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/cats/edit.html.erb
<h1>Edit cat</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<h1>List of Cats</h1>
 
 <%= link_to 'Add a new cat', new_cat_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
	<th>Breed</th>
	<th>Gender</th>
	<th colspan="3"></th>
  </tr>
 
  <% @cats.each do |cat| %>
    <tr>
      <td><%= cat.name %></td>
      <td><%= cat.color %></td>
	  <td><%= cat.race %></td>
	  <td><%= cat.gender %></td>
	  <td><%= link_to 'Show', cat_path(cat) %></td>
      <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
      <td><%= link_to 'Destroy', cat_path(cat), method: :delete, data: { confirm: 'Are you sure you want to delete this cat?' } %></td>	  
    </tr>
  <% end %>
</table>

app/views/cats/new.html.erb
<h1>New cat</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>
 
<p>
  <strong>Color:</strong>
  <%= @cat.color %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @cat.race %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @cat.gender %>
</p>


<%= link_to 'Edit', edit_cat_path(@cat) %> 
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyGettingStarted</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :defaults %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listenerstats/index.html.erb
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<style type="text/css">
${demo.css}
		</style>
		<script type="text/javascript">
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Monthly Average Rainfall'
        },
        subtitle: {
            text: 'Source: WorldClimate.com'
        },
        xAxis: {
            categories: [
                'Jan',
                'Feb',
                'Mar',
                'Apr',
                'May',
                'Jun',
                'Jul',
                'Aug',
                'Sep',
                'Oct',
                'Nov',
                'Dec'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Rainfall (mm)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Tokyo',
            data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

        }, {
            name: 'New York',
            data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

        }, {
            name: 'London',
            data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

        }, {
            name: 'Berlin',
            data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

        }]
    });
});
		</script>



<h1>Listener statistics</h1>
<br>
<b>Name of last fm listener:</b>
<br>
<%= @name %>
<br>
<b>Start date to begin collecting the top songs listened to:</b>
<br>
<%= @startDate %><br>
<b>End date:
</b>
<br>
<%= @endDate %>
<br>
<hr>
<h2>Important Development notes:</h2>
<p>
		The presence of this page shows the successful implementation of an unbound form and that the information provided in the previous page is available for use (last fm listener name, start date, and end date).
</p>		
<p>
	With this information, the controller can use APIs to retrieve listening statistics and present it in a graphical form.
</p>	
	The two API's that are required to be used:
	<br>
	http://www.last.fm/api/show/user.getRecentTracks
	<br>
	http://www.highcharts.com
	<br>
	<br>
<b>Note</b> that instead of using calendar_date_select,  which I spent a lot of time trying to use in the Rails environment, I used jQuery's datepicker. Datepicker seems to be currently recommended by developers over the now older calendar_date_select. However if calendar_date_select is necessary, more investigation would need to be done to allow it to be included into the project. Currently my unresolved problem is that although the gem appeared to be installed correctly, calendar_date_select cannot be found.
	<br>
	<br>
	<b>Some things todo:</b>
	<br>
	<ul>
		<li>Validate valid input for listener name, and dates, before presenting this page</li>
		<li>Disallow datepicker to choose a date in the future</li>
		<li>include APIs getRecentTracks and highcharts to present the statistics</li>
		<li>use calendar_date_select in place of jQuery's datepicker</li>
	</ul> 
	<hr>

	
<h2>An example of the kind of charts available for use when this challenge is fully implemented:</h2>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<hr>


 
 
 

app/views/welcome/index.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
 <script src="//code.jquery.com/jquery-1.10.2.js"></script>
 <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
 <link rel="stylesheet" href="/resources/demos/style.css">
  <script>
  $(function() {
    $( "#from" ).datepicker({
      defaultDate: "-1w",
      changeMonth: true,
      numberOfMonths: 2,
      onClose: function( selectedDate ) {
        $( "#to" ).datepicker( "option", "minDate", selectedDate );
      }
    });
    $( "#to" ).datepicker({
      defaultDate: "-1d",
      changeMonth: true,
      numberOfMonths: 2,
      onClose: function( selectedDate ) {
        $( "#from" ).datepicker( "option", "maxDate", selectedDate );
      }
    });
  });
  </script>


<h1>Practise with Ruby and Brett's Programming challenge.</h1>

<p>
[Updated 2016-05-08 Sunday]
</p>

 
<h2>Challenge 1 - Last.fm</h2>
Status: Unfinished.
<br>
<br> Please enter a last fm listener's name and the beginning and end date for the listening history you wish to retrieve for that listener, and press Submit: 
<br> 
<%= form_tag(listenerstats_path, :method=>'post') do %>
	Listener's name:
	<%= text_field_tag "listenerName" %> <br />
	<label for="from">From</label>
	<input type="text" id="from" name="from">
	<label for="to">to</label>
	<input type="text" id="to" name="to">
	<%= submit_tag 'Submit' %>
<% end %>
<hr>
<h2>Challenge 2 - Cat Database</h2>
<%= link_to 'Cats database', controller: 'cats' %>
<br>
<hr>
<h2>Challenge 2b - Cat Database in Scala</h2>
Status: Not done
<hr>
<h2>Challenge 3 - Responsive data visualisation</h2>
Status: Not done
<hr>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>